services:
  postgres:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: agent-api
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=database
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=dc76ad3137c861a8a4cf15b4284eca902be7485a81af89b84769f93050a8febd
  # TODO Rust, Cpp
